### ISSUE TITLE
Fix different sized pictures

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/2017-phd-students#33]
At the moment the different profile pictures are all different sizes on our page at https://alan-turing-institute.github.io/2017-phd-students/.

Does anyone have any good ideas on how to fix that? I think forcing them to be a specific size seems like a sensible idea.

**Comment by nathancunn** [comment]
Just committed change to index.html to fix the width of profile pictures. No limit on height but I guess they'll all be reasonably consistent.

**Comment by KirstieJane** [comment]
Thank you @nathancunn! Looks great! 🙌
