### ISSUE TITLE
Make consistent picture sizing more robust

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/2017-phd-students#38]
The fix for issue #33 to make all pictures the same width requires the addition of a `style="width:200px"` attribute to the `img` tab of each profile picture.

However, it is easy to forget to update this when pasting in a new `img` tab from somewhere else. We should make this a setting that is set once and applied to all profile pictures.

**Comment by sparkle-sparkle** [comment]
I can help you with a more robust solution for the width of the profile pictures. Can I do this for you?

**Comment by sparkle-sparkle** [comment]
I have a working solution for you, ready to push, I do need the permissions to do so. I'm not allowed to push to the branch 'kirstie-picture-width-fix'.

**Comment by martintoreilly** [comment]
Fixed by @sparkle-sparkle in PR #41 and merged into branch `kirstie-picture-width-fix`. Will merge into `gh-pages` via PR #39 .

**Comment by martintoreilly** [comment]
Thanks for the help @sparkle-sparkle.

**Comment by martintoreilly** [comment]
Merged into `gh-pages` via PR #39

**Comment by sparkle-sparkle** [comment]
You're welcome @martintoreilly. I'm glad I could help 😄
